# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(788, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.card_picture = QtWidgets.QLabel(self.centralwidget)
        self.card_picture.setGeometry(QtCore.QRect(540, 50, 221, 301))
        self.card_picture.setObjectName("card_picture")
        self.search_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_button.setGeometry(QtCore.QRect(450, 10, 85, 27))
        self.search_button.setObjectName("search_button")
        self.search_type = QtWidgets.QComboBox(self.centralwidget)
        self.search_type.setGeometry(QtCore.QRect(10, 10, 71, 28))
        self.search_type.setObjectName("search_type")
        self.search_type.addItem("")
        self.search_type.addItem("")
        self.search_type.addItem("")
        self.card_info = QtWidgets.QTextBrowser(self.centralwidget)
        self.card_info.setGeometry(QtCore.QRect(520, 360, 256, 192))
        self.card_info.setObjectName("card_info")
        self.search_result_widget = QtWidgets.QListWidget(self.centralwidget)
        self.search_result_widget.setGeometry(QtCore.QRect(10, 50, 256, 501))
        self.search_result_widget.setObjectName("search_result_widget")
        self.history_button = QtWidgets.QPushButton(self.centralwidget)
        self.history_button.setGeometry(QtCore.QRect(90, 10, 31, 27))
        self.history_button.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.history_button.setObjectName("history_button")
        self.search_keyword_edit = QtWidgets.QComboBox(self.centralwidget)
        self.search_keyword_edit.setGeometry(QtCore.QRect(130, 10, 311, 31))
        self.search_keyword_edit.setEditable(True)
        self.search_keyword_edit.setObjectName("search_keyword_edit")
        self.monster_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.monster_checkBox.setGeometry(QtCore.QRect(280, 80, 51, 21))
        self.monster_checkBox.setObjectName("monster_checkBox")
        self.spell_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.spell_checkBox.setGeometry(QtCore.QRect(330, 80, 51, 21))
        self.spell_checkBox.setObjectName("spell_checkBox")
        self.trap_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.trap_checkBox.setGeometry(QtCore.QRect(380, 80, 51, 21))
        self.trap_checkBox.setObjectName("trap_checkBox")
        self.monster_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.monster_groupBox.setGeometry(QtCore.QRect(280, 110, 231, 101))
        self.monster_groupBox.setObjectName("monster_groupBox")
        self.monster_normal_checkBox = QtWidgets.QCheckBox(self.monster_groupBox)
        self.monster_normal_checkBox.setEnabled(False)
        self.monster_normal_checkBox.setGeometry(QtCore.QRect(10, 20, 51, 21))
        self.monster_normal_checkBox.setObjectName("monster_normal_checkBox")
        self.monster_effect_checkBox = QtWidgets.QCheckBox(self.monster_groupBox)
        self.monster_effect_checkBox.setEnabled(False)
        self.monster_effect_checkBox.setGeometry(QtCore.QRect(60, 20, 51, 21))
        self.monster_effect_checkBox.setObjectName("monster_effect_checkBox")
        self.monster_tuner_checkBox = QtWidgets.QCheckBox(self.monster_groupBox)
        self.monster_tuner_checkBox.setEnabled(False)
        self.monster_tuner_checkBox.setGeometry(QtCore.QRect(110, 20, 51, 21))
        self.monster_tuner_checkBox.setObjectName("monster_tuner_checkBox")
        self.monster_token_checkBox = QtWidgets.QCheckBox(self.monster_groupBox)
        self.monster_token_checkBox.setEnabled(False)
        self.monster_token_checkBox.setGeometry(QtCore.QRect(160, 20, 61, 21))
        self.monster_token_checkBox.setObjectName("monster_token_checkBox")
        self.monster_dual_checkBox = QtWidgets.QCheckBox(self.monster_groupBox)
        self.monster_dual_checkBox.setEnabled(False)
        self.monster_dual_checkBox.setGeometry(QtCore.QRect(10, 40, 51, 21))
        self.monster_dual_checkBox.setObjectName("monster_dual_checkBox")
        self.monster_toon_checkBox = QtWidgets.QCheckBox(self.monster_groupBox)
        self.monster_toon_checkBox.setEnabled(False)
        self.monster_toon_checkBox.setGeometry(QtCore.QRect(60, 40, 51, 21))
        self.monster_toon_checkBox.setObjectName("monster_toon_checkBox")
        self.monster_spirit_checkBox = QtWidgets.QCheckBox(self.monster_groupBox)
        self.monster_spirit_checkBox.setEnabled(False)
        self.monster_spirit_checkBox.setGeometry(QtCore.QRect(110, 40, 51, 21))
        self.monster_spirit_checkBox.setObjectName("monster_spirit_checkBox")
        self.monster_ritual_checkBox = QtWidgets.QCheckBox(self.monster_groupBox)
        self.monster_ritual_checkBox.setEnabled(False)
        self.monster_ritual_checkBox.setGeometry(QtCore.QRect(60, 80, 51, 21))
        self.monster_ritual_checkBox.setObjectName("monster_ritual_checkBox")
        self.monster_fusion_checkBox = QtWidgets.QCheckBox(self.monster_groupBox)
        self.monster_fusion_checkBox.setEnabled(False)
        self.monster_fusion_checkBox.setGeometry(QtCore.QRect(10, 60, 51, 21))
        self.monster_fusion_checkBox.setObjectName("monster_fusion_checkBox")
        self.monster_xyz_checkBox = QtWidgets.QCheckBox(self.monster_groupBox)
        self.monster_xyz_checkBox.setEnabled(False)
        self.monster_xyz_checkBox.setGeometry(QtCore.QRect(60, 60, 51, 21))
        self.monster_xyz_checkBox.setObjectName("monster_xyz_checkBox")
        self.monster_synchro_checkBox = QtWidgets.QCheckBox(self.monster_groupBox)
        self.monster_synchro_checkBox.setEnabled(False)
        self.monster_synchro_checkBox.setGeometry(QtCore.QRect(110, 60, 51, 21))
        self.monster_synchro_checkBox.setObjectName("monster_synchro_checkBox")
        self.monster_pendulum_checkBox = QtWidgets.QCheckBox(self.monster_groupBox)
        self.monster_pendulum_checkBox.setEnabled(False)
        self.monster_pendulum_checkBox.setGeometry(QtCore.QRect(160, 60, 51, 21))
        self.monster_pendulum_checkBox.setObjectName("monster_pendulum_checkBox")
        self.monster_link_checkBox = QtWidgets.QCheckBox(self.monster_groupBox)
        self.monster_link_checkBox.setEnabled(False)
        self.monster_link_checkBox.setGeometry(QtCore.QRect(10, 80, 51, 21))
        self.monster_link_checkBox.setObjectName("monster_link_checkBox")
        self.monster_spsummon_checkBox = QtWidgets.QCheckBox(self.monster_groupBox)
        self.monster_spsummon_checkBox.setEnabled(False)
        self.monster_spsummon_checkBox.setGeometry(QtCore.QRect(160, 40, 71, 21))
        self.monster_spsummon_checkBox.setObjectName("monster_spsummon_checkBox")
        self.spell_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.spell_groupBox.setGeometry(QtCore.QRect(280, 220, 231, 71))
        self.spell_groupBox.setObjectName("spell_groupBox")
        self.spell_normal_checkBox = QtWidgets.QCheckBox(self.spell_groupBox)
        self.spell_normal_checkBox.setEnabled(False)
        self.spell_normal_checkBox.setGeometry(QtCore.QRect(10, 20, 51, 21))
        self.spell_normal_checkBox.setObjectName("spell_normal_checkBox")
        self.spell_continuous_checkBox = QtWidgets.QCheckBox(self.spell_groupBox)
        self.spell_continuous_checkBox.setEnabled(False)
        self.spell_continuous_checkBox.setGeometry(QtCore.QRect(60, 20, 51, 21))
        self.spell_continuous_checkBox.setObjectName("spell_continuous_checkBox")
        self.spell_quickplay_checkBox = QtWidgets.QCheckBox(self.spell_groupBox)
        self.spell_quickplay_checkBox.setEnabled(False)
        self.spell_quickplay_checkBox.setGeometry(QtCore.QRect(110, 20, 51, 21))
        self.spell_quickplay_checkBox.setObjectName("spell_quickplay_checkBox")
        self.spell_field_checkBox = QtWidgets.QCheckBox(self.spell_groupBox)
        self.spell_field_checkBox.setEnabled(False)
        self.spell_field_checkBox.setGeometry(QtCore.QRect(160, 20, 61, 21))
        self.spell_field_checkBox.setObjectName("spell_field_checkBox")
        self.spell_equip_checkBox = QtWidgets.QCheckBox(self.spell_groupBox)
        self.spell_equip_checkBox.setEnabled(False)
        self.spell_equip_checkBox.setGeometry(QtCore.QRect(10, 40, 51, 21))
        self.spell_equip_checkBox.setObjectName("spell_equip_checkBox")
        self.spell_ritual_checkBox = QtWidgets.QCheckBox(self.spell_groupBox)
        self.spell_ritual_checkBox.setEnabled(False)
        self.spell_ritual_checkBox.setGeometry(QtCore.QRect(60, 40, 51, 21))
        self.spell_ritual_checkBox.setObjectName("spell_ritual_checkBox")
        self.trap_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.trap_groupBox.setGeometry(QtCore.QRect(280, 300, 231, 51))
        self.trap_groupBox.setObjectName("trap_groupBox")
        self.trap_normal_checkBox = QtWidgets.QCheckBox(self.trap_groupBox)
        self.trap_normal_checkBox.setEnabled(False)
        self.trap_normal_checkBox.setGeometry(QtCore.QRect(10, 20, 51, 21))
        self.trap_normal_checkBox.setObjectName("trap_normal_checkBox")
        self.trap_continuous_checkBox = QtWidgets.QCheckBox(self.trap_groupBox)
        self.trap_continuous_checkBox.setEnabled(False)
        self.trap_continuous_checkBox.setGeometry(QtCore.QRect(60, 20, 51, 21))
        self.trap_continuous_checkBox.setObjectName("trap_continuous_checkBox")
        self.trap_counter_checkBox = QtWidgets.QCheckBox(self.trap_groupBox)
        self.trap_counter_checkBox.setEnabled(False)
        self.trap_counter_checkBox.setGeometry(QtCore.QRect(110, 20, 51, 21))
        self.trap_counter_checkBox.setObjectName("trap_counter_checkBox")
        self.attack_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.attack_edit.setEnabled(False)
        self.attack_edit.setGeometry(QtCore.QRect(320, 360, 71, 23))
        self.attack_edit.setText("")
        self.attack_edit.setObjectName("attack_edit")
        self.attack = QtWidgets.QLabel(self.centralwidget)
        self.attack.setGeometry(QtCore.QRect(280, 360, 41, 16))
        self.attack.setObjectName("attack")
        self.defense_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.defense_edit.setEnabled(False)
        self.defense_edit.setGeometry(QtCore.QRect(440, 360, 71, 23))
        self.defense_edit.setText("")
        self.defense_edit.setObjectName("defense_edit")
        self.defense = QtWidgets.QLabel(self.centralwidget)
        self.defense.setGeometry(QtCore.QRect(400, 360, 41, 16))
        self.defense.setObjectName("defense")
        self.level_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.level_edit.setEnabled(False)
        self.level_edit.setGeometry(QtCore.QRect(320, 390, 71, 23))
        self.level_edit.setText("")
        self.level_edit.setObjectName("level_edit")
        self.level = QtWidgets.QLabel(self.centralwidget)
        self.level.setGeometry(QtCore.QRect(280, 390, 41, 16))
        self.level.setObjectName("level")
        self.pendulum_scales_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.pendulum_scales_edit.setEnabled(False)
        self.pendulum_scales_edit.setGeometry(QtCore.QRect(340, 420, 71, 23))
        self.pendulum_scales_edit.setText("")
        self.pendulum_scales_edit.setObjectName("pendulum_scales_edit")
        self.pendulum_scales = QtWidgets.QLabel(self.centralwidget)
        self.pendulum_scales.setGeometry(QtCore.QRect(280, 420, 61, 16))
        self.pendulum_scales.setObjectName("pendulum_scales")
        self.xyz_rank_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.xyz_rank_edit.setEnabled(False)
        self.xyz_rank_edit.setGeometry(QtCore.QRect(340, 450, 71, 23))
        self.xyz_rank_edit.setText("")
        self.xyz_rank_edit.setObjectName("xyz_rank_edit")
        self.xyz_rank = QtWidgets.QLabel(self.centralwidget)
        self.xyz_rank.setGeometry(QtCore.QRect(280, 450, 61, 16))
        self.xyz_rank.setObjectName("xyz_rank")
        self.link_num = QtWidgets.QLabel(self.centralwidget)
        self.link_num.setGeometry(QtCore.QRect(400, 390, 41, 16))
        self.link_num.setObjectName("link_num")
        self.link_num_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.link_num_edit.setEnabled(False)
        self.link_num_edit.setGeometry(QtCore.QRect(440, 390, 71, 23))
        self.link_num_edit.setText("")
        self.link_num_edit.setObjectName("link_num_edit")
        self.filter_text = QtWidgets.QLabel(self.centralwidget)
        self.filter_text.setGeometry(QtCore.QRect(280, 50, 91, 16))
        self.filter_text.setObjectName("filter_text")
        self.total_label = QtWidgets.QLabel(self.centralwidget)
        self.total_label.setGeometry(QtCore.QRect(550, 15, 231, 20))
        self.total_label.setText("")
        self.total_label.setObjectName("total_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 788, 20))
        self.menubar.setObjectName("menubar")
        self.tools_menu = QtWidgets.QMenu(self.menubar)
        self.tools_menu.setObjectName("tools_menu")
        self.help_menu = QtWidgets.QMenu(self.menubar)
        self.help_menu.setObjectName("help_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.setting_action = QtWidgets.QAction(MainWindow)
        self.setting_action.setObjectName("setting_action")
        self.about_action = QtWidgets.QAction(MainWindow)
        self.about_action.setObjectName("about_action")
        self.official_website_action = QtWidgets.QAction(MainWindow)
        self.official_website_action.setObjectName("official_website_action")
        self.card_count_action = QtWidgets.QAction(MainWindow)
        self.card_count_action.setObjectName("card_count_action")
        self.word_study_action = QtWidgets.QAction(MainWindow)
        self.word_study_action.setObjectName("word_study_action")
        self.tools_menu.addAction(self.setting_action)
        self.tools_menu.addAction(self.card_count_action)
        self.tools_menu.addAction(self.word_study_action)
        self.help_menu.addAction(self.about_action)
        self.help_menu.addAction(self.official_website_action)
        self.menubar.addAction(self.tools_menu.menuAction())
        self.menubar.addAction(self.help_menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "游戏王离线查卡器"))
        self.card_picture.setText(_translate("MainWindow", "TextLabel"))
        self.search_button.setText(_translate("MainWindow", "搜索"))
        self.search_type.setItemText(0, _translate("MainWindow", "卡名"))
        self.search_type.setItemText(1, _translate("MainWindow", "卡密"))
        self.search_type.setItemText(2, _translate("MainWindow", "描述"))
        self.history_button.setText(_translate("MainWindow", "⇦"))
        self.monster_checkBox.setText(_translate("MainWindow", "怪兽"))
        self.spell_checkBox.setText(_translate("MainWindow", "魔法"))
        self.trap_checkBox.setText(_translate("MainWindow", "陷阱"))
        self.monster_groupBox.setTitle(_translate("MainWindow", "怪兽类型"))
        self.monster_normal_checkBox.setText(_translate("MainWindow", "通常"))
        self.monster_effect_checkBox.setText(_translate("MainWindow", "效果"))
        self.monster_tuner_checkBox.setText(_translate("MainWindow", "调整"))
        self.monster_token_checkBox.setText(_translate("MainWindow", "衍生物"))
        self.monster_dual_checkBox.setText(_translate("MainWindow", "二重"))
        self.monster_toon_checkBox.setText(_translate("MainWindow", "卡通"))
        self.monster_spirit_checkBox.setText(_translate("MainWindow", "灵魂"))
        self.monster_ritual_checkBox.setText(_translate("MainWindow", "仪式"))
        self.monster_fusion_checkBox.setText(_translate("MainWindow", "融合"))
        self.monster_xyz_checkBox.setText(_translate("MainWindow", "超量"))
        self.monster_synchro_checkBox.setText(_translate("MainWindow", "同调"))
        self.monster_pendulum_checkBox.setText(_translate("MainWindow", "灵摆"))
        self.monster_link_checkBox.setText(_translate("MainWindow", "连接"))
        self.monster_spsummon_checkBox.setText(_translate("MainWindow", "特殊召唤"))
        self.spell_groupBox.setTitle(_translate("MainWindow", "魔法卡类型"))
        self.spell_normal_checkBox.setText(_translate("MainWindow", "通常"))
        self.spell_continuous_checkBox.setText(_translate("MainWindow", "永续"))
        self.spell_quickplay_checkBox.setText(_translate("MainWindow", "速攻"))
        self.spell_field_checkBox.setText(_translate("MainWindow", "场地"))
        self.spell_equip_checkBox.setText(_translate("MainWindow", "装备"))
        self.spell_ritual_checkBox.setText(_translate("MainWindow", "仪式"))
        self.trap_groupBox.setTitle(_translate("MainWindow", "陷阱卡类型"))
        self.trap_normal_checkBox.setText(_translate("MainWindow", "通常"))
        self.trap_continuous_checkBox.setText(_translate("MainWindow", "永续"))
        self.trap_counter_checkBox.setText(_translate("MainWindow", "反击"))
        self.attack.setText(_translate("MainWindow", "ATT："))
        self.defense.setText(_translate("MainWindow", "DEF："))
        self.level.setText(_translate("MainWindow", "等级："))
        self.pendulum_scales.setText(_translate("MainWindow", "灵摆刻度："))
        self.xyz_rank.setText(_translate("MainWindow", "超量阶级："))
        self.link_num.setText(_translate("MainWindow", "LINK："))
        self.filter_text.setText(_translate("MainWindow", "高级过滤条件："))
        self.tools_menu.setTitle(_translate("MainWindow", "工具"))
        self.help_menu.setTitle(_translate("MainWindow", "帮助"))
        self.setting_action.setText(_translate("MainWindow", "设置"))
        self.about_action.setText(_translate("MainWindow", "关于"))
        self.official_website_action.setText(_translate("MainWindow", "官网"))
        self.card_count_action.setText(_translate("MainWindow", "数据统计"))
        self.word_study_action.setText(_translate("MainWindow", "词汇学习"))
